### ISSUE TITLE
Doesn't work with node.js (4.x)

### ISSUE THREAD

**Issue by welksonramos** [Loknar/node-winsay#4]
update edge.js dependency to latest version for nodejs 4.x support

**Comment by Loknar** [comment]
thanks for pointing this out, I'll take a look this evening

**Comment by welksonramos** [comment]
Nice!  :clap: :clap: :clap:

**Comment by Loknar** [comment]
https://github.com/Loknar/node-winsay/commit/ce701ab188b1d0fbff9a684e23a0e50a610d7447 that should do it
